pcc\WebBundle\Entity\Measure:
    type: entity
    table: measure
    indexes:
        fk_id_city:
            columns:
                - id_city
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        temperature:
            type: float
            nullable: false
            precision: 10
            scale: 0
        pressure:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        idCity:
            targetEntity: City
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_city:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
